default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: '0522'
  socket: /var/lib/mysql/mysql.sock

production:
  <<: *default
  database: furima-42613_production
  host: 127.0.0.1