default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: sh1n_tera
  password: sh1ng0522
  host: localhost
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: furima_db

test:
  <<: *default
  database: furima_test

production:
  <<: *default
  database: furima_db
