default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: furima_dev
  username: postgres
  password: 
  host: localhost

test:
  <<: *default
  database: furima_test
  username: postgres
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: furima-42613_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
